# ===============================
# Application Info
# ===============================
spring.application.name=api-gateway
server.port=8383

# ===============================
# Eureka Client
# ===============================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# ===============================
# Spring Cloud Gateway
# ===============================
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# ===============================
# Manual Routes (Recommended)
# ===============================

# ---- Auth Service ----
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://auth-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/tourismgov/v1/auth/**

# ---- User Service ----
spring.cloud.gateway.routes[1].id=user-service
spring.cloud.gateway.routes[1].uri=lb://user-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/tourismgov/v1/users/**


# ===============================
# Config Server
# ===============================
spring.config.import=optional:configserver:http://localhost:8181