# ================================
# Application Information
# ================================
spring.application.name=EurekaServer
server.port=8761

# ================================
# Eureka Server Configuration
# ================================

# Eureka server should NOT register itself
eureka.client.register-with-eureka=false

# Eureka server should NOT fetch registry
eureka.client.fetch-registry=false

# Prevents mass eviction during network issues
eureka.server.enable-self-preservation=true

# ================================
# Actuator (Optional but Recommended)
# ================================
management.endpoints.web.exposure.include=health,info