package com.cognizant.compliance.dto;

import java.time.LocalDateTime;

import com.cognizant.compliance.enums.ComplianceResult;
import com.cognizant.compliance.enums.ComplianceType;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.PastOrPresent;
import jakarta.validation.constraints.Size;
import lombok.Data;

@Data
public class ComplianceRecordRequestDTO {

    @Size(max = 50, message = "Reference number cannot exceed 50 characters")
    private String referenceNumber; // Could be optional if auto-generated by the backend

    @NotNull(message = "Entity ID is required (e.g., the Site ID or Event ID)")
    private Long entityId;

    @NotNull(message = "Compliance type is required")
    private ComplianceType type;

    @NotNull(message = "Compliance result is required")
    private ComplianceResult result;

    @NotNull(message = "Date of compliance check is required")
    @PastOrPresent(message = "Date cannot be in the future")
    private LocalDateTime date;

    private String notes;
}