spring.application.name=GatewayAPI
server.port=8282
spring.cloud.gateway.enabled=true

spring.cloud.gateway.routes[0].id=UserService
spring.cloud.gateway.routes[0].uri=http://localhost:8282
spring.cloud.gateway.routes[0].predicates[0]=Path=/tourismgov/user/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1