# ===============================
# Application Info
# ===============================
spring.application.name=GatewayAPI
server.port=8383

# ===============================
# Eureka Client
# ===============================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# ===============================
# Spring Cloud Gateway
# ===============================
# Disable discovery locator when using manual routes
spring.cloud.gateway.discovery.locator.enabled=false
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# ===============================
# Gateway Routes
# ===============================

spring.cloud.gateway.routes[0].id=UserService
spring.cloud.gateway.routes[0].uri=lb://UserService
spring.cloud.gateway.routes[0].predicates[0]=Path=/tourismgov/user/**


spring.config.import=optional:configserver:http://localhost:8181