spring.application.name=TouristService


server.port=8283
spring.web.error.include-message=always

spring.datasource.url=jdbc:mysql://localhost:3306/TouristDB?createDatabaseIfNotExist=true

# Port 8282 is where your User Service is running
user.service.url=http://localhost:8282
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.config.import = optional:configserver:http://localhost:8181